[package]
name = "dcbor"
version = "0.7.6"
edition = "2021"
description = "Deterministic CBOR (\"dCBOR\") for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-dcbor-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/dcbor"

[dependencies]
chrono = "0.4.23"
half = "=2.2.1"
hex = "0.4.3"

[dev-dependencies]
indoc = "2.0.0"
version-sync = "0.9"
hex-literal = "0.4.1"
