[package]
name = "dcbor"
version = "0.1.1"
edition = "2021"
license-file = "LICENSE.md"
description = "Deterministic CBOR (\"dCBOR\") for Rust."
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-dcbor-rust"
readme = "README.md"
categories = ["data-structures", "encoding"]

[dependencies]
chrono = "0.4.23"

[dev-dependencies]
indoc = "2.0.0"
