[package]
name = "dcbor"
version = "0.11.0"
edition = "2021"
description = "Deterministic CBOR (\"dCBOR\") for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-dcbor-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/dcbor"

[dependencies]
chrono = "0.4.28"
half = "=2.2.1"
hex = "0.4.3"
thiserror = "1.0.48"
anyhow = "1.0"
bytes = "1.5.0"

[dev-dependencies]
indoc = "2.0.0"
version-sync = "0.9"
hex-literal = "0.4.1"

[features]
multithreaded = []
